### ISSUE TITLE
Can't send message, can't get the free trial.

### ISSUE THREAD

**Issue by okimazzi** [BrakusTapus/AetherBox#10]
Hello. I wanna test this plugin, and I can send you a message to use the free trial option
![image](https://github.com/BrakusTapus/AetherBox/assets/47760399/e584790f-6eb1-4494-81e1-6e1178d62f1b)

**Comment by BrakusTapus** [comment]
> Hello. I wanna test this plugin, and I can send you a message to use the free trial option ![image](https://private-user-images.githubusercontent.com/47760399/342034619-e584790f-6eb1-4494-81e1-6e1178d62f1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNDQ0NTAsIm5iZiI6MTcxOTE0NDE1MCwicGF0aCI6Ii80Nzc2MDM5OS8zNDIwMzQ2MTktZTU4NDc5MGYtNmViMS00NDk0LTgxZTEtNmUxMTc4ZDYyZjFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDEyMDIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0OTM5YWFiZjlkN2JjZDI5ZDU5YTg4YTRlZmFiYTBhMzRkYWM0Y2YxZDk2NTE0YmUzODBlOTM2MWUwYzU5OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XZbPbSD2MvwFW9qQuDw32W02CaK-ZRpMFhax6teiVWw)

Have you tried turning it off and on again?
